In [1]:
import numpy as np
x=np.arange(16)

In [2]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
#返回2，5，8位置元素
[x[3],x[5],x[8]]

[3, 5, 8]

In [4]:
ind = [ 3,5,8]
x[ind]

array([3, 5, 8])

In [6]:
ind = np.array([[0,2],[1,3]])
x[ind]#上侧为索引，下侧为值

array([[0, 2],
       [1, 3]])

In [7]:
X=x.reshape(4,-1)

In [8]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
row = np.array([0,1,2])
col = np.array([1,2,3])
X[row,col]#相当于访问对应坐标点

array([ 1,  6, 11])

In [11]:
X[0,col]#固定x和对应y

array([1, 2, 3])

In [15]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
##bool索引  
col=[True,False,True,True]#为True返回，为False不返回
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [18]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [20]:
2*x==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
np.sum(x<=3)

4

In [25]:
np.count_nonzero(x<=3)

4

In [28]:
np.any(x<=0)

True

In [30]:
np.all(x>=0)

True

In [32]:
np.sum(X%2==0,axis=1)#看每行多少个偶数

array([2, 2, 2, 2])

In [33]:
np.sum(X%2==0,axis=0)#看每列多少个偶数

array([4, 0, 4, 0])

In [34]:
np.all(X>0,axis=0)#每列是否全大于零

array([False,  True,  True,  True])

In [37]:
np.sum((x>3)&(x<10))#并且用位操作符&

6

In [38]:
np.sum((x%2==0)|(x>10))#或运算符

11

In [40]:
#非运算符

np.sum(~(x==0))#非运算符



15

In [41]:
x[x<5]#判断数组中小于五的数

array([0, 1, 2, 3, 4])

In [42]:
x[x%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [43]:
X[X[:,3]%3==0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [44]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])