In [1]:
import numpy as np


In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X= x.reshape(2,5)

In [4]:
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
#基本属性
x.ndim  # 维度

1

In [6]:
X.ndim

2

In [7]:
#shape 
x.shape

(10,)

In [8]:
X.shape

(2, 5)

In [9]:
#size 元素个数
x.size

10

In [10]:
X.size

10

In [11]:
#numpy数据访问
x[-1]

9

In [12]:
X[1][2]#不建议用

7

In [13]:
X[(0,4)]#括号内为坐标,无括号也可以

4

In [14]:
X[1,2]

7

In [15]:
X[1]

array([5, 6, 7, 8, 9])

In [16]:
X[-2,-1]

4

In [17]:
#切片
x[0:5]

array([0, 1, 2, 3, 4])

In [18]:
X[:2,0:3:2]  #,前是对行操作，后是对列操作

array([[0, 2],
       [5, 7]])

In [19]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [20]:
X[0,2:4]#降维

array([2, 3])

In [21]:
X[:,0]

array([0, 5])

In [22]:
subX = X[:2,:3]

In [23]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [24]:
subX[0,0]= 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [25]:
X#子矩阵会影响原矩阵，

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [26]:
subX = X[:2,:3].copy()#copy副本不会对原矩阵产生影响

In [27]:
subX[0,0]=99


In [28]:
subX

array([[99,  1,  2],
       [ 5,  6,  7]])

In [29]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [30]:
#reshape
x.reshape(2,5)

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [31]:
x.reshape(-1,10)#-1表示不操作，由系统决定

array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9]])

In [32]:
x.reshape(2,-1)

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [33]:
X[1,1:3]

array([6, 7])