In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
%%timeit
sum(L)

100000 loops, best of 3: 10.9 µs per loop


In [4]:
%%timeit
np.sum(L)

The slowest run took 18.76 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.92 µs per loop


In [5]:
big_array = np.random.rand(1000000)#均匀分布


In [6]:
%%timeit
sum(big_array)

10 loops, best of 3: 89.1 ms per loop


In [7]:
%%timeit
np.sum(big_array)

1000 loops, best of 3: 998 µs per loop


In [8]:
np.min(big_array)

5.206357717169041e-07

In [9]:
#面向对象写法
big_array.min()


5.206357717169041e-07

In [10]:
big_array.max()

0.9999989756963108

In [11]:
#多维度聚合操作
X = np.arange(16).reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)#所有元素和

120

In [13]:
np.sum(X,axis=0)#垂直方向和

array([24, 28, 32, 36])

In [14]:
np.sum(X,axis=1)#水平方向

array([ 6, 22, 38, 54])

In [15]:
np.prod(X)#所有元素积

0

In [16]:
np.mean(X)#均值

7.5

In [17]:
np.median(X)#返回中位数

7.5

In [18]:
v=np.array([1,1,2,2,10])

In [19]:
v.mean()

3.2

In [20]:
np.median(v)

2.0

In [21]:
#取百分比位置值
np.percentile(v,q=50)

2.0

In [22]:
np.percentile(v,q=100)

10.0

In [23]:
for percent in [0,25,50,75,100]:
    print( np.percentile(v,q=percent))

1.0
1.0
2.0
2.0
10.0


In [24]:
np.var(v)#方差

11.76

In [25]:
np.std(v)#标准差

3.4292856398964493

In [26]:
big_array = np.random.randn(1000000)#均匀分布，均值为0，方差为1

In [27]:
np.var(big_array)

0.9993278467041289

In [28]:
np.std(big_array)

0.9996638668593203

In [29]:
np.mean(big_array)

0.0006404793423742715

NameError: name 'x' is not defined