In [1]:
import numpy as np
#arg是在给定一定的要求下x的取值

In [2]:
x= np.random.normal(0,1,1000000)#正态分布随机数 （均值，方差，个数）

In [3]:
np.min(x)

-4.71815886115944

In [4]:
np.argmin(x)#返回最小值索引

39849

In [5]:
x[39849]

-4.71815886115944

In [6]:
np.argmax(x)

355737

In [7]:
x[355737]

4.739785630247826

In [8]:
np.max(x)

4.739785630247826

In [11]:
x= np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.random.shuffle(x)#随机乱序
x

array([ 1,  4, 10,  7, 14,  9, 13, 11, 15, 12,  8,  3,  6,  5,  2,  0])

In [14]:
#正序排序
np.sort(x)#不对x进新修改

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
x

array([ 1,  4, 10,  7, 14,  9, 13, 11, 15, 12,  8,  3,  6,  5,  2,  0])

In [16]:
x.sort()

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
#二维排序
X=np.random.randint(10,size=(4,4))

In [19]:
X

array([[3, 5, 4, 8],
       [7, 0, 3, 2],
       [6, 5, 1, 4],
       [0, 5, 1, 4]])

In [25]:
np.sort(X)#默认每一行正序排序（axis=-1或=1），每一列正序axis=0

AxisError: axis 2 is out of bounds for array of dimension 2

In [26]:
np.random.shuffle(x)

In [27]:
x

array([15,  1,  2, 12,  8, 11,  9,  3, 10,  5,  4, 13, 14,  7,  6,  0])

In [28]:
np.argsort(x)#返回正序排序索引

array([15,  1,  2,  7, 10,  9, 14, 13,  4,  6,  8,  5,  3, 11, 12,  0],
      dtype=int64)

In [29]:
x

array([15,  1,  2, 12,  8, 11,  9,  3, 10,  5,  4, 13, 14,  7,  6,  0])

In [40]:
np.partition(x,4)#类似一次归并排序，左侧小于，右侧大于标定点

array([ 1,  0,  2,  3,  4,  5,  6,  7,  8, 11, 10, 13, 14, 12,  9, 15])

In [34]:
np.argpartition(x,4)

array([ 1, 15,  2,  7, 10,  9, 14, 13,  4,  5,  8, 11, 12,  3,  6,  0],
      dtype=int64)

In [32]:
np.argsort(X)

array([[0, 2, 1, 3],
       [1, 3, 2, 0],
       [2, 3, 1, 0],
       [0, 2, 3, 1]], dtype=int64)

In [33]:
X

array([[3, 5, 4, 8],
       [7, 0, 3, 2],
       [6, 5, 1, 4],
       [0, 5, 1, 4]])