In [1]:
n=10
L=[i for i in range(n)]
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np
L=np.array(L)
L*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
%%timeit #统计运行时间
a = [e*2 for e in L ]

The slowest run took 8.63 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.62 µs per loop


In [4]:
%%timeit
L*2

The slowest run took 33.36 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 645 ns per loop


In [5]:
#对矩阵的运算 universal function



In [6]:
X=np.arange(1,16).reshape(3,5)

In [7]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [8]:
Y=np.arange(1,16).reshape(5,3)

In [9]:
X//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [10]:
X/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [11]:
X%2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [12]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [14]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [15]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [16]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [17]:
#矩阵间运算
A= np.arange(4).reshape(2,2)
B=np.full((2,2),10)

In [18]:
A+B

array([[10, 11],
       [12, 13]])

In [19]:
A*B#点乘

array([[ 0, 10],
       [20, 30]])

In [20]:
A.dot(B)#矩阵相乘

array([[10, 10],
       [50, 50]])

In [21]:
A.T#转置

array([[0, 2],
       [1, 3]])

In [22]:
C= np.full((3,3),666)

In [23]:
A+C


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [24]:
v= np.array([1,2])
A

array([[0, 1],
       [2, 3]])

In [25]:
v+A
#广播机制  每行对应位置都加上去

array([[1, 3],
       [3, 5]])

In [29]:
invA=np.linalg.inv(A)#矩阵求逆

In [30]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])