In [1]:
import numpy as np


## python list

In [2]:
List = [i for i in range(10)]
List

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
List[5]= 100

In [4]:
List

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [5]:
List[5]='aaa'
List

[0, 1, 2, 3, 4, 'aaa', 6, 7, 8, 9]

不约束元素类型，但是性能低，因为需要检查每一个的类型。

In [6]:
import array

In [7]:
arr = array.array('i',[i for i in range(10)])#数组

In [8]:
arr[5]

5

In [9]:
arr[5]='hello'

TypeError: an integer is required (got type str)

In [10]:
#优点：效率高 缺点： 只能存数字，当做二维数组，没有匹配看成向量或者矩阵的运算

## numpy


In [11]:
nparr = np.array([i  for i in range(5)])

In [12]:
#进行一次隐式转换，截位操作

In [13]:
nparr

array([0, 1, 2, 3, 4])

In [14]:
nparr[3]=100

In [15]:
nparr

array([  0,   1,   2, 100,   4])

In [16]:
nparr[3]='he'

ValueError: invalid literal for int() with base 10: 'he'

In [17]:
nparr[1]=3.99#进行隐式转换，下取整

In [18]:
nparr

array([  0,   3,   2, 100,   4])

In [19]:
#机器学习和数据分析使用浮点数


In [20]:
ar=np.array([1,2,3.0])

In [21]:
ar.dtype

dtype('float64')

In [22]:
z=np.zeros(10,dtype=int )

In [23]:
z.astype(float)#类型转化

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

- 传入一个元组参数

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones(shape=(3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.full((3,5),fill_value=666.6)

array([[666.6, 666.6, 666.6, 666.6, 666.6],
       [666.6, 666.6, 666.6, 666.6, 666.6],
       [666.6, 666.6, 666.6, 666.6, 666.6]])

In [30]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
np.arange(30,20,-0.2)#步长可正可负可小数，range不行

array([30. , 29.8, 29.6, 29.4, 29.2, 29. , 28.8, 28.6, 28.4, 28.2, 28. ,
       27.8, 27.6, 27.4, 27.2, 27. , 26.8, 26.6, 26.4, 26.2, 26. , 25.8,
       25.6, 25.4, 25.2, 25. , 24.8, 24.6, 24.4, 24.2, 24. , 23.8, 23.6,
       23.4, 23.2, 23. , 22.8, 22.6, 22.4, 22.2, 22. , 21.8, 21.6, 21.4,
       21.2, 21. , 20.8, 20.6, 20.4, 20.2])

In [32]:
# linspace等差数列左闭右闭
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [33]:
#随机数
import random
random.randint(9,10)#左闭右闭

9

In [34]:
np.random.randint(9,10,size = 3)#左闭右开

array([9, 9, 9])

In [35]:
#生成一个三行五列矩阵
np.random.randint(0,10,size=(3,5))

array([[2, 2, 1, 6, 1],
       [1, 2, 1, 4, 2],
       [6, 7, 2, 7, 0]])

In [36]:
#生成随机浮点数
np.random.random(size=(3,4,5))#生成[0，1）随机浮点数

array([[[0.44235195, 0.50077982, 0.00791217, 0.17459915, 0.55766763],
        [0.98682502, 0.76206277, 0.3014156 , 0.94606387, 0.78916475],
        [0.52558131, 0.71013802, 0.81548738, 0.2890874 , 0.46156778],
        [0.32966507, 0.67006288, 0.11623643, 0.31529543, 0.31262171]],

       [[0.77352171, 0.69571549, 0.96241271, 0.88886076, 0.53517629],
        [0.55482655, 0.35906863, 0.76768553, 0.67595198, 0.97155374],
        [0.94975125, 0.13088917, 0.10880397, 0.76143794, 0.76766038],
        [0.96332925, 0.3599762 , 0.270809  , 0.71519015, 0.15142369]],

       [[0.73236797, 0.11072366, 0.60259296, 0.37485813, 0.32209321],
        [0.60361251, 0.5264734 , 0.16532458, 0.90858599, 0.38549018],
        [0.4035506 , 0.29758609, 0.19824494, 0.43907365, 0.71944183],
        [0.49188939, 0.99157703, 0.3110844 , 0.89721528, 0.08640849]]])

In [37]:
np.random.normal()#均值为0，方差为1的随机浮点数

-0.5743310170113822

np.random.normal(loc=10,scale=100)#均值为loc，方差为scale的随机浮点数