In [1]:
import numpy as np

In [2]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#切割 列表内为切割点，分割区间为左闭右开
x1,x2,x3=np.split(x,[3,7])

In [4]:
x3

array([7, 8, 9])

In [5]:
x1,x2=np.split(x,[3])

In [6]:
x1


array([0, 1, 2])

In [7]:
x2

array([3, 4, 5, 6, 7, 8, 9])

In [24]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a1,a2=np.split(a,[2])#默认按行(垂直方向)切割

In [10]:
np.split(a,[2],axis=1)#axis操作轴

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [11]:
 np.vsplit(a,[2])#垂直分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [12]:
np.hsplit(a,[2])#水平切割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [13]:
#合并
x= np.array([1,2,3])

In [14]:
y= np.array([3,2,1])

In [25]:
x+y

array([4, 4, 4])

In [15]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [16]:
z=np.array([666,666,666])

In [17]:
np.concatenate([x,y,z])#一维合成向量

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [18]:
A=np.array([[1,2,3],
          [4,5,6]])

In [19]:
np.concatenate([A,A],axis=1)#合成由axis，默认垂直方向合成，只能处理相同维度

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [20]:
#可以reshape为相同维度
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [21]:
#合并方向维度要相同
np.vstack([A,z])#比concatenate更智能

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [22]:
B=np.full((2,2),10)

In [23]:
np.hstack([A,B])

array([[ 1,  2,  3, 10, 10],
       [ 4,  5,  6, 10, 10]])